on:
  release:
    types:
      - published
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup XMake
        uses: xmake-io/github-action-setup-xmake@v1
      
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - name: Update Repo
        run: xmake repo -u

      - name: Update Project
        run: xmake f -a x64 -m release -p windows -v -y

      - name: Build Project
        run: xmake -v -y

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ModApi-${{ github.sha }}
          path: bin/

  upload-to-release:
    needs:
      - build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download bin artifact
        uses: actions/download-artifact@v4
        with:
          name: ModApi-${{ github.sha }}

      - name: Copy additional files to mod directory
        run: cp CHANGELOG.md dll/

      - name: Create Mod Package
        run: |
          cd dll
          zip -r ../ModApi-windows-x64.zip *

      - name: Create SDK Package
        run: zip -r ModApi-SDK.zip include/ lib/

      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          files: |
            *.zip
            pdb/*.pdb